### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by JunOno09** [JunOno09/furima-32508#9]
# 入力内容 

自身のフリマアプリのURL 
https://furima-32508.herokuapp.com
Basic認証のIDとパスワード | 
ID :admin
pasword:2222

出品者用のメールアドレスとパスワード | 本番環境にて商品出品しているユーザーの情報
アドレス:a11111.com
ニックネーム:a1
password:a11111

購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報
アドレス:b11111i.com
ニックネーム：め
password:b11111
購入用カードの番号・期限・セキュリティコード | PAY.JPのテストカード情報
number:4242424242424242
期限:　3/33
CVC: 123

よろしくおねがいします！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の
商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう！**
現状、商品出品者が売却済みの商品編集ページへ遷移しようとすると遷移できてしまいます。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by JunOno09** [comment]
お世話になります。

出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の
商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう！

の修正完了いたしました。
挙動確認のほど、よろしくおねがいします！

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項は修正が確認できました！
ありがとうございます。

もう1点追加で修正していただきたい箇所がございます。
ご確認よろしくお願いいたします！

### [修正依頼箇所]

- [x] **ログイン状態の出品者でも、売却済みの商品に対しては「編集・削除ボタン」が表示されないようにしましょう！**

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by JunOno09** [comment]
お世話になります。

ログイン状態の出品者でも、売却済みの商品に対しては「編集・削除ボタン」が表示されないようにしましょう！

の修正完了いたしました。
挙動確認のほど、よろしくおねがいします！

**Comment by takumi0530** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、前回の指摘事項は修正が確認できました！
ありがとうございます。

もう1点追加で修正していただきたい箇所がございます。
ご確認よろしくお願いいたします！

**[修正依頼箇所]**
 - [x] **商品出品時に登録した情報が見られるようになっていること**
 詳細画面の「商品説明」欄が空欄になっています。

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by JunOno09** [comment]
お世話になります。

商品出品時に登録した情報が見られるようになっていること

の修正完了いたしました。
挙動確認のほど、よろしくおねがいします！

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/103257092-230e5100-49d3-11eb-8c1c-6c581ac15ae9.png)
